repos:
  - repo: local
    hooks:
      - id: code-quality-checks
        name: Run pre-commit checks (format, sort-imports, check-mypy)
        entry: bash -c 'make format && make check-sort-imports && make check-types'
        language: system
        pass_filenames: false
