repos:
  - repo: local
    hooks:
      - id: code-quality-checks
        name: Run pre-commit checks (format, sort-imports, check-mypy)
        entry: bash -c 'make format && make check-sort-imports && make check-types'
        language: system
        pass_filenames: false
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        name: Check spelling
        args:
          - --write-changes
          - --skip=*.pyc,*.pyo,*.lock,*.git,*.mypy_cache,__pycache__,*.egg-info,.pytest_cache,docs/_build,env,venv,.venv
          - --ignore-words-list=enginee
