repos:
  - repo: local
    hooks:
      - id: poetry-checks
        name: Run pre-commit checks (format, sort-imports, check-mypy)
        entry: bash -c 'poetry run format && poetry run sort-imports && poetry run check-mypy'
        language: system
        pass_filenames: false