name: 'Run Service Tests'
description: 'Run the full RedisVL service test suite with all API integrations'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
  uv-version:
    description: 'uv version to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Cache HuggingFace Models
      uses: actions/cache@v5
      with:
        path: hf_cache
        key: ${{ runner.os }}-hf-cache

    - name: Set HuggingFace token
      shell: bash
      run: |
        mkdir -p ~/.huggingface
        echo '{"token":"$HF_TOKEN"}' > ~/.huggingface/token

    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: true
        python-version: ${{ inputs.python-version }}
        cache-dependency-glob: |
          pyproject.toml
          uv.lock

    - name: Install required dependencies
      shell: bash
      run: |
        uv sync

    - name: Test module imports
      shell: bash
      run: |
        uv run python -m tests.test_imports redisvl

    - name: Install all dependencies
      shell: bash
      run: |
        uv sync --all-extras

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ env.GOOGLE_CREDENTIALS }}

    - name: Run full test suite
      shell: bash
      run: |
        make test-all
